/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;


import AccesoBaseDeDatos.Tipo_trasladoData;
import AccesoBaseDeDatos.TrasladoData;
import agenciadeturismoproyecto.Conectar;
import agenciadeturismoproyecto.Tipo_traslado;
import agenciadeturismoproyecto.Traslado;
/**
 *
 * @author G5
 */
public class FormularioTraslado extends javax.swing.JInternalFrame {
    
private TrasladoData trasladoData;
private Tipo_trasladoData tipo_trasladoData; 
private Conectar con;

    /**
     * Creates new form Traslado
     */
    public FormularioTraslado() {
        initComponents();
       
        con=new Conectar();
        trasladoData = new TrasladoData(con);
        tipo_trasladoData = new Tipo_trasladoData(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRminibus = new javax.swing.JRadioButton();
        jRvan = new javax.swing.JRadioButton();
        jRauto = new javax.swing.JRadioButton();
        tfId = new javax.swing.JTextField();
        tfcantidad = new javax.swing.JTextField();
        tfcosto = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jBlimpiar = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        tftipo = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Formulario Traslado");

        jLabel2.setText("Id_Traslado:");

        jLabel3.setText("Tipo:");

        jLabel4.setText("Cantidad Max.Personas:");

        jLabel5.setText("Costo por Km:");

        bTipo.add(jRminibus);
        jRminibus.setText("Minibus");
        jRminibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRminibusActionPerformed(evt);
            }
        });

        bTipo.add(jRvan);
        jRvan.setText("Van");

        bTipo.add(jRauto);
        jRauto.setText("Auto");
        jRauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRautoActionPerformed(evt);
            }
        });

        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jBguardar.setText("Guardar");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jBmodificar.setText("Modificar");
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });

        jBeliminar.setText("Eliminar");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });

        jBlimpiar.setText("Limpiar");
        jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiarActionPerformed(evt);
            }
        });

        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(98, 98, 98))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBguardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBmodificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBeliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBlimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfcosto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tftipo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jRauto)
                                            .addComponent(jRminibus)
                                            .addComponent(jRvan)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel3)))
                                .addGap(87, 87, 87)
                                .addComponent(jBbuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRauto)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRvan)
                            .addComponent(tftipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRminibus)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfcosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBguardar)
                            .addComponent(jBmodificar)
                            .addComponent(jBeliminar)
                            .addComponent(jBlimpiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBsalir)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRautoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRautoActionPerformed

    private void jRminibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRminibusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRminibusActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
int id_traslado= Integer.parseInt(tfId.getText());
        trasladoData.borrarTraslado(id_traslado);        // TODO add your handling code here:
    }//GEN-LAST:event_jBeliminarActionPerformed
/*private String tipo(){
        String tipo;
    if (jRauto.isSelected())
    {return tipo = "Auto";}
    if (jRvan.isSelected())
    { return tipo = "Van";}
       if (jRminibus.isSelected())
       {return tipo ="Minibus";}
        return null;
       
} */

    private int VistatipoTrasporte(){
        
        int Tipo=0;
        if (jRauto.isSelected()){
        Tipo = 1;
        
        }
        else{
           if (jRvan.isSelected()){
           Tipo = 3;
           }
           else{
            Tipo = 2;
           }
            }
        
        return Tipo;
        
    }

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
 
Tipo_traslado tipo_traslado = new Tipo_traslado();
Traslado traslado = new Traslado();

tipo_traslado = tipo_trasladoData.buscarTipo_traslado(VistatipoTrasporte());
 

traslado.setMiTipo_traslado(tipo_traslado);
traslado.setCantidadDePasajeros(Integer.parseInt(tfcantidad.getText()));
traslado.setCostoPorKm(Double.parseDouble(tfcosto.getText()));
trasladoData.guardarTraslado(traslado);
tfId.setText(Integer.toString(traslado.getId_traslado()));        // TODO add your handling code here:
    }//GEN-LAST:event_jBguardarActionPerformed

    
    
    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
    int id_traslado= Integer.parseInt(tfId.getText());
        
        Traslado traslado =trasladoData.buscarTraslado(id_traslado);
        tfId.setText(traslado.getId_traslado()+"");
        tftipo.setText(traslado.getMiTipo_traslado().getNombre());
        tfcantidad.setText(Integer.toString(traslado.getCantidadDePasajeros()));
        tfcosto.setText(Double.toString(traslado.getCostoPorKm()) );        // TODO add your handling code here:
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
      tfId.setText("");
       tftipo.setText("");
       tfcantidad.setText ("");
       
       jRauto.setSelected(false);
       jRvan.setSelected(false);
       jRminibus.setSelected(false);
       tfcosto.setText ("");        // TODO add your handling code here:
    }//GEN-LAST:event_jBlimpiarActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
if ((tfId.getText())!=null){
            
            Tipo_traslado tipo = new Tipo_traslado();
             
            tipo = tipo_trasladoData.buscarTipo_traslado(VistatipoTrasporte()); 
            int cantidadDePasajeros = Integer.parseInt(tfcantidad.getText());
            
            double costoPorKm= Double.parseDouble(tfcosto.getText());
           

             Traslado traslado =new Traslado(Integer.parseInt(tfId.getText()),tipo, cantidadDePasajeros ,costoPorKm);
             trasladoData.actualizarTraslado(traslado);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBmodificarActionPerformed

    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bTipo;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRauto;
    private javax.swing.JRadioButton jRminibus;
    private javax.swing.JRadioButton jRvan;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfcantidad;
    private javax.swing.JTextField tfcosto;
    private javax.swing.JTextField tftipo;
    // End of variables declaration//GEN-END:variables
}
